[WIP] 设置页面
Clipteam/clipcc-gui pull request #110
Opened 2022-03-20 06:17 UTC by alexcui03

## 设置页面

状态：阶段 2（开发中）

本分支为 ClipCC 编辑器重构了原有的设置页面，并增加了对扩展设置的相关设置。

![image](https://user-images.githubusercontent.com/30141313/159150483-7cae6f78-6edc-4f95-bf47-243267e0c5ca.png)

### 具体更改：
- [x] 重构设置页面，删除冗余代码，优化原有代码逻辑
- [ ] 使用下拉框控件替换原有的选择控件
- [x] 使用 text input 替换原有的 number input，并实现 max、min、precision 等属性
- [x] 支持从扩展的 settings.json 加载扩展
- [ ] 支持扩展访问设置项的值
- [ ] 支持暗色模式
- [x] 使用 firefox 滚动条相关 css 属性避免可能的兼容性问题
- [x] 实现侧边栏以快速定位到设置项

2022-03-26 10:04 UTC, Steve-xmh approved these changes

2022-03-26 10:17 UTC, alexcui03 commented
我都没写完你就approve🤔

________________________________
From: SteveXMH ***@***.***>
Sent: Saturday, March 26, 2022, 6:04 PM
To: Clipteam/clipcc-gui ***@***.***>
Cc: Alex Cui ***@***.***>; Author ***@***.***>
Subject: Re: [Clipteam/clipcc-gui] [WIP] 设置页面 (PR #110)


@Steve-xmh approved this pull request.

—
Reply to this email directly, view it on GitHub<https://github.com/Clipteam/clipcc-gui/pull/110#pullrequestreview-922302430>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHF6XAPSF5XTEDBZ6L33QLDVB3OMJANCNFSM5RFBZIUQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-04 13:31 UTC, SimonShiki requested changes
改完了再review

2022-04-10 11:04 UTC, SimonShiki reviewed
等待完成optional扩展根据选项保存

2022-04-11 06:23 UTC, merged